version: "3.8"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api.dev
    ports:
      - "3000:3000"
    volumes:
      - ./api:/app/api
  web:
    build:
      context: .
      dockerfile: Dockerfile.web.dev
    ports:
      - "3001:3001"
    volumes:
      - ./web:/app/web
    environment:
      - DOCKER_ENV=true
